// Generated by CoffeeScript 1.3.3
(function() {
  var $, html;

  $ = jQuery.noConflict();

  html = {
    tasks: $('#tasks'),
    tasklists: $('#tasklists'),
    addTaskList: function(tl) {
      return this.tasklists.append(this.getTaskListHtml(tl));
    },
    addTask: function(t, list) {
      return list.append(this.getTaskHtml(t));
    },
    getTaskListHtml: function(tl) {
      var listitem;
      listitem = ($('<li>')).append("<h2>" + tl.title + "</h2>").append(this.tasks.html());
      return listitem;
    },
    getTaskHtml: function(t) {
      var checkbox, listitem;
      checkbox = $('<input type="checkbox" class="checkbox">');
      listitem = ($('<li>')).append(checkbox).append("[" + t.time + "] ").append(t.name);
      checkbox.click(function() {
        if (checkbox.is(':checked')) {
          t.completed = true;
          return listitem.addClass('completed');
        } else {
          t.completed = false;
          return listitem.removeClass('completed');
        }
      });
      return listitem;
    }
  };

  window.project = {
    addTaskList: function(form) {
      var tl;
      if (form.title.value) {
        tl = {
          title: form.title.value
        };
        html.addTaskList(tl);
        form.title.value = '';
      }
      return false;
    },
    addTask: function(form) {
      var t;
      if (form.message.value) {
        t = {
          name: form.message.value,
          time: parseFloat(form.time.value.replace(',', '.')) || 0,
          assigned: parseInt(form.assigned.value),
          completed: false
        };
        html.addTask(t, $('.tasks', ($(form)).parent()));
        form.message.value = '';
        form.time.value = '';
        form.assigned.value = '';
        ($(form.message)).focus();
      }
      return false;
    },
    showTaskForm: function(button) {
      ($(button)).hide();
      return ($('.add-task-form', ($(button)).parent())).show();
    }
  };

}).call(this);
